### PR TITLE
fix ElementHandle#check and ElementHandle#uncheck to work

### LINKED ISSUE #63: Using "check" on radiobutton element leads to ArgumentError: unknown keyword: position
### Step To Reproduce / Observed behavior
 page.query_selector("#database_modus_host").check
raises "ArgumentError: unknown keyword: position"

It calls
playwright-ruby-client-0.5.2/lib/playwright_api/element_handle.rb:134:in `check'
which calls 
playwright-ruby-client-0.5.2/lib/playwright/channel_owners/element_handle.rb:234:in `check'
with parameter "position:" which is not defined in element_handle.rb:234

### Expected behavior
selecting radio button without error 

### Environment

Paste the output of `ruby --version`
jruby-9.2.17.0

Workaround exists in still using click instead of check.

### PR DESCRIPTION
**Pull request by YusukeIwaki**
resolves #63

### CODE REVIEW

File: spec/integration/page/check_spec.rb [hunk 1]
```diff
@@ -9,6 +9,14 @@
     end
   end
 
+  it 'should check the box with ElementHandle#check' do
```
Comment (YusukeIwaki) [inline spec/integration/page/check_spec.rb:12]: Without fix, this spec fails as expected.

```
Failures:

  1) Page#check should check the box with ElementHandle#check
     Failure/Error:
             def check(force: nil, noWaitAfter: nil, timeout: nil)
               params = {
                 force: force,
                 noWaitAfter:  noWaitAfter,
                 timeout: timeout,
               }.compact
               @channel.send_message_to_server('check', params)
       
               nil
             end
     
     ArgumentError:
       unknown keyword: :position
     # ./lib/playwright/channel_owners/element_handle.rb:233:in `check'
     # ./lib/playwright_api/element_handle.rb:134:in `check'
     # ./spec/integration/page/check_spec.rb:15:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:82:in `with_page'
     # ./spec/integration/page/check_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:49:in `block (4 levels) in <top (required)>'
     # ./lib/playwright/playwright_api.rb:114:in `block in wrap_block_call'
     # ./lib/playwright/channel_owners/browser_type.rb:17:in `launch'
     # ./lib/playwright_api/browser_type.rb:135:in `launch'
     # ./spec/spec_helper.rb:42:in `block (3 levels) in <top (required)>'
     # ./lib/playwright.rb:76:in `create'
     # ./spec/spec_helper.rb:39:in `block (2 levels) in <top (required)>'

  2) Page#check should uncheck the box with ElementHandle#uncheck
     Failure/Error:
             def uncheck(force: nil, noWaitAfter: nil, timeout: nil)
               params = {
                 force: force,
                 noWaitAfter:  noWaitAfter,
                 timeout: timeout,
               }.compact
               @channel.send_message_to_server('uncheck', params)
       
               nil
             end
     
     ArgumentError:
       unknown keyword: :position
     # ./lib/playwright/channel_owners/element_handle.rb:244:in `uncheck'
     # ./lib/playwright_api/element_handle.rb:646:in `uncheck'
     # ./spec/integration/page/check_spec.rb:39:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:82:in `with_page'
     # ./spec/integration/page/check_spec.rb:37:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:49:in `block (4 levels) in <top (required)>'
     # ./lib/playwright/playwright_api.rb:114:in `block in wrap_block_call'
     # ./lib/playwright/channel_owners/browser_type.rb:17:in `launch'
     # ./lib/playwright_api/browser_type.rb:135:in `launch'
     # ./spec/spec_helper.rb:42:in `block (3 levels) in <top (required)>'
     # ./lib/playwright.rb:76:in `create'
     # ./spec/spec_helper.rb:39:in `block (2 levels) in <top (required)>'

Finished in 20.23 seconds (files took 0.77033 seconds to load)
15 examples, 2 failures

Failed examples:

rspec ./spec/integration/page/check_spec.rb:12 # Page#check should check the box with ElementHandle#check
rspec ./spec/integration/page/check_spec.rb:36 # Page#check should uncheck the box with ElementHandle#uncheck

```
